### ISSUE TITLE
multiple PZEM 016 devices on 1 serial bus

### ISSUE THREAD

**Issue by Thoppo14** [BrucesHobbies/energyMaster#2]
For a larger project I want to do, measuring 3 phase current and voltage is necessary.
The setup will be at least 4 PZEM 016 devices, the problem here is that a Raspberry Pi only has 4 USB ports and that is not enough.

Is there a way to merge multiple signals to one serial bus using a RS485 to USB module with your code?

I already have used your program for a smaller project at home and it is amazing, works perfectly!
Without all your work I certainly couldn't do it.

**Comment by BrucesHobbies** [comment]
Yes, from their documentation it looks like you can change the address but the documentation is minimal. I will look at writing a simple utility to change the address. I will try and get to it in the next week or two.

**Comment by Thoppo14** [comment]
Thank in advance, I'm really looking forward to a possible solution!
At this moment I'm trying to bypass this problem with a NodeMCU ESP82660, but there are still some cummunication issues.

**Comment by BrucesHobbies** [comment]
I added a quick function to set the module's device address. Only a single device should be on the RS-485 bus. The program takes two command line arguments: old_address  and new_address. For example: python3 poem.py 1 2 would change the address from 1 to 2. The module address change is retained through power cycles. Note RS-485 should only have a single termination resistor at each end of the twisted pair bus. PZEM's have a termination resistor in each unit which may impact communication reliability when using multiple units on a bus.
